export {
  addExternalPathsToIndex,
  addToCollection,
  execAsync,
  getIndexName,
  listCollections,
  multiGet,
  type QmdOptions,
  type SearchOptions,
  type SearchResult,
  type SearchType,
  search,
  updateEmbeddings,
  updateIndex,
} from './cli.js';
